# Generated by Django 5.2.7 on 2025-10-04 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolontariat_krakow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='data_wyslania',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 4, 22, 21, 45, 861517, tzinfo=datetime.timezone.utc)),
        ),
    ]
