# Generated by Django 5.2.7 on 2025-10-05 00:48

import datetime
import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolontariat_krakow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='data_wyslania',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 5, 0, 48, 18, 324910, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='oferta',
            name='lokalizacja',
            field=models.CharField(default='Kraków', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Zlecenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_ukonczone', models.BooleanField(default=False)),
                ('czy_potwierdzone', models.BooleanField(default=False)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zlecenia', to='wolontariat_krakow.oferta')),
                ('wolontariusz', models.ManyToManyField(limit_choices_to={'rola': 'wolontariusz'}, related_name='zlecenia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
