# Generated by Django 5.2.7 on 2025-10-05 01:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolontariat_krakow', '0002_oferta_data_wyslania_oferta_lokalizacja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='data_wyslania',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
