# Generated by Django 5.2.7 on 2025-10-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolontariat_krakow', '0003_alter_oferta_data_wyslania'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='czas_trwania',
            field=models.CharField(blank=True, help_text='Przewidywany czas trwania (np. 2 godziny, 3 dni)', max_length=50),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tematyka',
            field=models.CharField(blank=True, help_text='Główna tematyka oferty (np. edukacja, pomoc seniorom)', max_length=100),
        ),
        migrations.AddField(
            model_name='oferta',
            name='wymagania',
            field=models.TextField(blank=True, help_text='Wymagania dla wolontariuszy'),
        ),
    ]
