# Generated by hand for adding 'wiek' field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolontariat_krakow', '0004_oferta_czas_trwania_oferta_tematyka_oferta_wymagania'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='wiek',
            field=models.PositiveSmallIntegerField(null=True, blank=True, help_text='Wiek (lata). Używane do rozróżniania małoletnich/pełnoletnich wolontariuszy'),
        ),
    ]

